---
x-templates:
  minecraft-server-environment: &minecraft-server-environment
    EULA: true
    TYPE: limbo
    LIMBO_BUILD: 59

  minecraft-server: &minecraft-server
    image: itzg/minecraft-server:latest
    network_mode: host
    environment:
      <<: *minecraft-server-environment

services:
  gate:
    image: kasefuchs/lazygate:latest
    network_mode: host
    build:
      context: ..
      dockerfile: build/Dockerfile

  limbo:
    <<: *minecraft-server
    volumes:
      - limbo:/data
    environment:
      <<: *minecraft-server-environment
      CUSTOM_SERVER_PROPERTIES: |
        server-port=33018
        tab-header=Limbo
        bungeecord=false
        allow-flight=true

  notorious:
    <<: *minecraft-server
    labels:
      lazygate.allocation.server: notorious
      lazygate.allocation.time.minimumOnline: 30s
      lazygate.allocation.time.inactivityThreshold: 30s
      lazygate.allocation.queues: send
    volumes:
      - notorious:/data
    environment:
      <<: *minecraft-server-environment
      CUSTOM_SERVER_PROPERTIES: |
        server-port=33019
        tab-header=Notorious
        bungeecord=false
        allow-flight=true

  luminescence:
    <<: *minecraft-server
    labels:
      lazygate.allocation.server: luminescence
      lazygate.allocation.time.minimumOnline: 2m
      lazygate.allocation.time.inactivityThreshold: 5m
      lazygate.allocation.queues: wait,kick
      lazygate.queue.wait.timeout: 10s
      lazygate.queue.wait.pingInterval: 2s
      lazygate.queue.kick.reason: Luminescence is currently starting!
    volumes:
      - luminescence:/data
    environment:
      <<: *minecraft-server-environment
      CUSTOM_SERVER_PROPERTIES: |
        server-port=33020
        tab-header=Luminescence
        bungeecord=false
        allow-flight=true

volumes:
  limbo: {}
  notorious: {}
  luminescence: {}
