---
repos:
  - repo: local
    hooks:
      - id: gofumpt-check
        name: check go formatting
        entry: scripts/gofumpt-check.sh
        types: [go]
        language: script

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: check-case-conflict
      - id: check-added-large-files
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
