---
config:
  bind: 0.0.0.0:25565
  servers:
    limbo: localhost:33018
    notorious: localhost:33019
    luminescence: localhost:33020
  try:
    - notorious
    - luminescence
  forwarding:
    mode: legacy
